apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp_poc
  name: {{ .Values.wordpress }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wp-poc
  type: LoadBalancer
status:
  loadBalancer: {}
